#!/bin/bash

h=100

# Get width
w=`convert /home/rene_r/.Background/octocat.jpg -format "%w" info:`

# Create gradient
rm -f /tmp/alpha_grad_src.png
convert -size ${w}x$h gradient:black-none /tmp/alpha_grad_src.png

# Crop and apply gradient
convert  /home/rene_r/.Background/simple.png -crop ${w}x${h}+0+0 \
/tmp/alpha_grad_src.png -compose CopyOpacity -composite \
output.png
